package com.amsis;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TrafficViolationInput implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TrafficViolationInput() {
    }




}